version: "3.8"
name: 'project4'
services:
  catalog-db:
    image: mysql:8.0
    container_name: catalog-db
    environment:
      - MYSQL_ROOT_PASSWORD=cisco
      - MYSQL_DATABASE=catalog
      - MYSQL_USER=cisco
      - MYSQL_PASSWORD=cisco
    ports:
      - "3306:3306"
    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U postgres"]
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p", "cisco"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m